project:
  name: @project.artifactId@

server:
  port: 10001


org:
  my:
    jwt:
      #跳过认证的路由
      skip-auth-urls:
        - /baidu
      ############################################
      #   有效时长
      #     单位：d:天、h:小时、m:分钟、s:秒
      ###########################################
      effective-time: 1h
